baseURL = "http://wideopen.github.io/"
languageCode = "en-us"
title = "Wide-Open Datawatch"


[[menu.main]]
  name   = "GEO"
  url    = "/geo/"
  weight = 10

[[menu.main]]
  name   = "SRA"
  url    = "/sra/"
  weight = 20

[[menu.main]]
  name   = "About"
  url    = "/about"
  weight = 30
